name: Deploy to GCP

on:
  push:
    branches:
      - master

env:
  PROJECT: acknowledge
  APP: lumen

jobs:
  deploy_client:
    name: Deploy client to Cloud Storage
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build
        run: |
          npm ci
          npm run build
        working-directory: ./client

      - name: Setup gcloud environment
        uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
        with:
          service_account_email: ${{ secrets.GCLOUD_EMAIL }}
          service_account_key: ${{ secrets.GCLOUD_AUTH }}

      - name: Deploy to Cloud Storage
        run: gsutil -m cp -r ./dist/** gs://lumen.ack.pt/
        working-directory: ./client
